TemplateClass and Processing pipeline for methods
geosciences-data-practicum/reanalysis_getter pull request #2
Opened 2020-09-28 13:23 UTC by ivanhigueram

## Main purpose
In this PR, I added one abstract class `jetstream.model.Template` that serves as a template for processing GCM (`jetstream.model.Model`) and reanalysis data (`jetstream.model.Analysis`). All classes are wrapping the functions we were using, but they have a more streamlined implementation, and there's a reduction in the memory footrprint since most of the methods are delayed properties of the class. 

As all abstract classes, there's abstract methods that are germane to each data product. Hence reading and cutting the input data is done on each class, and not on the `Template`. A "one-liner" function: `pipeline_methods()` run the whole processing for one file and save the file if a `save_path` is specified on the class instantiation. 

## Additional Infrastructure 
A `setup.py` was added. This is useful to avoid import problems with `dask.distributed` since it avoids the uber-problem of 
picking and serializing functions that aren't in the worker environment, also, we have a library that we can import as `import jetstream`, and that is extremely cool. 

Ideally, this would be the first step to additional classes or objects relying on them for plotting or other steps towards publication.

2020-09-28 19:24 UTC, afarah18 commented on jetstream/analyzer.py
> +Basic I/O functions to load/unload xarray data from reanalysis
this is great

2020-09-30 02:16 UTC, afarah18 requested changes
`t_prime_calculation.ipynb` is too latge for github to load but i noticed it seems outdated. Maybe change it to work with the following, if it is truly meant to be an example of how to run the calc.
```
from jetstream.model.template import Template
from jetstream.model.model import Model

subset_data = {'time': slice('2020-01-01', '2021-01-01')}

model = Model(path_to_files='/project2/geos39650/jet_stream/data/processed_winters/ScenarioMIP_NCAR_CESM2-WACCM_ssp585_day.nc4',
          path_to_save_files='/home/afarah/',
          subset_dict=subset_data)
```

2020-09-30 02:16 UTC, afarah18 commented on env/.project_env
> +DATA_FOLDER='/project2/'
this seems problematic but ill try it before i suggest a change

2020-09-30 02:16 UTC, afarah18 commented on requirements.txt
>  iris
we dont need iris and it causes a lot of dependency issues

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +        self.outvars=['t_ref', 't_prime', self.temp_var]
self.temp_var isnt defined?

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +        - cdf_areas (np.array or pd.Series) Cumulative area.
can you specify the units here? like if R_EARTH is always in km, cdf_areas needs to be a cdf of areas that are in km^2

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +
we should again specify units: temps need to be in kelvin, area_weights need to be in unit(R_EARTH)^2 pdf_lat_effs needs to be a pdf of something in degrees

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +    def t_prime_calculation(self):
imma be honest i dont fully understand this function because of all the dask but i trust that its right because weve seen all those plots with T' using this code

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +        """ Movinig average demean array results on xarray object
i feel like this should take the boxcar width as an input

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +        total_demean = total.groupby('time.dayofyear') - time_days
time_days isnt defined

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +            df['boxcar'] = df.t_prime.rolling(window='10D')
ok yeah this isnt what we want but it seems like you dont actually use this function so we can fix it later

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +        self.outvars=['t_ref', 't_prime', self.temp_var]
oops, yes it is. its defined later in the individual Model and Analysis classes

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +from descriptors import cachedproperty
have to specifically install this - is there a way to do that while installing this library in the `setup.py`?

2020-09-30 02:16 UTC, afarah18 commented on jetstream/model/template.py
> +from descriptors import cachedproperty
I had to do `pip install Dickens --user` for this to work

2020-09-30 02:16 UTC, afarah18 commented on infrastructure/load_stuff.sh
cant make a suggestion on the whole file b/c github but please change this filed to be your working version :)

2020-10-11 21:54 UTC, ivanhigueram commented
Done with all changes! Re-tested the rolling window, and it's very much sub-optimal 😢

2020-10-29 15:44 UTC, afarah18 approved these changes
Note that the user still has to install `Dickens` via `pip install Dickens --user` for the template file to load. Issue is with `descriptors` and `cached property`.

Also, the boxcar demean still doesn't work but we will do this in post-processing anyway. Maybe in future iterations we can get rid of demeaning in processing and create a separate file for post-proc that has all our post-proc functions and the user who runs this can just specify which things they want.

In all, its functional and its what we need for processing!

2020-11-04 16:41 UTC, merged